/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.DAOBuku;
import control.DAOMember;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.Buku;
import model.Member;


public class PanelMember extends javax.swing.JPanel implements ListSelectionListener{

    /**
     * Creates new form PanelMember
     */
    Member oldmember;
    Member newmember;
    public static DAOMember daomember;
    DefaultTableModel dtmmember;
    public PanelMember() {
        initComponents();
        daomember = new DAOMember();
        //dtmBuku menampung model tabelBuku
        dtmmember = (DefaultTableModel) tabelMember.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public  void reset(){
        InputIDMember.setText("");
        InputAlamat.setText("");
        InputKontak.setText("");
        InputNama.setText("");
        InputTanggalLahir.setText("");
        InputStatus.setSelected(false);
        tampilDataMahasiswaTOJTable();
    }
    public static DAOMember getDaoMember() {
        return daomember ;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelKelolaMember = new javax.swing.JLabel();
        LabelDataMember = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMember = new javax.swing.JTable();
        LabelIDMember = new javax.swing.JLabel();
        InputIDMember = new javax.swing.JTextField();
        LabelNama = new javax.swing.JLabel();
        InputNama = new javax.swing.JTextField();
        LabelKontak = new javax.swing.JLabel();
        InputKontak = new javax.swing.JFormattedTextField();
        LabelTanggalLahir = new javax.swing.JLabel();
        InputTanggalLahir = new javax.swing.JTextField();
        LabelAlamat = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        InputAlamat = new javax.swing.JTextArea();
        LabelStatus = new javax.swing.JLabel();
        InputStatus = new javax.swing.JCheckBox();
        btnSimpan = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        LabelKelolaMember.setText("Kelola Member");

        LabelDataMember.setText("Master Data Member");

        tabelMember.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID ", "Nama", "Alamat", "Kontak", "Tgl Lahir", "Status"
            }
        ));
        jScrollPane1.setViewportView(tabelMember);

        LabelIDMember.setText("ID Member");

        LabelNama.setText("Nama");

        LabelKontak.setText("Kontak");

        try {
            InputKontak.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("############")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        InputKontak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputKontakActionPerformed(evt);
            }
        });

        LabelTanggalLahir.setText("Tanggal Lahir");

        LabelAlamat.setText("Alamat");

        InputAlamat.setColumns(20);
        InputAlamat.setRows(5);
        jScrollPane2.setViewportView(InputAlamat);

        LabelStatus.setText("Status");

        InputStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputStatusActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelIDMember)
                            .addComponent(LabelKelolaMember)
                            .addComponent(LabelNama)
                            .addComponent(LabelKontak))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InputIDMember, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(InputNama)
                            .addComponent(InputKontak)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelAlamat)
                            .addComponent(LabelStatus))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InputStatus)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelTanggalLahir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(InputTanggalLahir)))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LabelDataMember)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelKelolaMember)
                    .addComponent(LabelDataMember))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelIDMember)
                            .addComponent(InputIDMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelNama)
                            .addComponent(InputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelKontak)
                            .addComponent(InputKontak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelTanggalLahir)
                            .addComponent(InputTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelAlamat)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelStatus)
                            .addComponent(InputStatus)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnSimpan)
                        .addGap(28, 28, 28)
                        .addComponent(btnReset)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
            if (InputIDMember.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "ID Member is required!", "Warning Message", JOptionPane.WARNING_MESSAGE);
            } else if (InputNama.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Nama is required!", "Warning Message", JOptionPane.WARNING_MESSAGE);
            } else if (InputAlamat.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Alamat is required!", "Warning Message", JOptionPane.WARNING_MESSAGE);
            } else if (InputKontak.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Kontak is required!", "Warning Message", JOptionPane.WARNING_MESSAGE);
            } else if (InputTanggalLahir.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Tanggal Lahir required!", "Warning Message", JOptionPane.WARNING_MESSAGE);
            } else if (InputStatus.isSelected() == false) {
                JOptionPane.showMessageDialog(this, "Stok required!", "Warning Message", JOptionPane.WARNING_MESSAGE);
            } else if (oldmember == null) { //Create
                //pada tahap ini digunakan untuk menambah data buku
                //1. masukkan data buku dari form input ke newBuku
                //2. Jika daoBuku.insertData(newBuku) --> true maka tampilkan dialog berhasil
                //3. Jika daoBuku.insertData(newBuku) --> false maka tampilkan dialog data buku sudah ada
                newmember = new Member();
                newmember.setId(InputIDMember.getText().trim());
                newmember.setNama(InputNama.getText().trim());
                newmember.setAlamat(InputAlamat.getText().trim());
                newmember.setKontak(InputKontak.getText().trim());
                newmember.setTanggallahir(InputTanggalLahir.getText().trim());
                newmember.setStatus(InputStatus.isSelected());
                daomember.insertData(newmember);
                reset();
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Format Tahun Terbit salah!", "Warning Message", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void InputKontakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputKontakActionPerformed
        
    }//GEN-LAST:event_InputKontakActionPerformed

    private void InputStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputStatusActionPerformed
        public void tampilDataMahasiswaTOJTable() {
        tabelMember.getSelectionModel().removeListSelectionListener(this);
        dtmmember.getDataVector().removeAllElements();
        for (Member b : daomember.getAllData()) {
            dtmmember.addRow(new Object[]{
                b.getId(),
                b.getNama(),
                b.getAlamat(),
                b.getKontak(),
                b.getTanggallahir(),
                b.isStatus()
            });
        }
        tabelMember.getSelectionModel().addListSelectionListener(this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea InputAlamat;
    private javax.swing.JTextField InputIDMember;
    private javax.swing.JFormattedTextField InputKontak;
    private javax.swing.JTextField InputNama;
    private javax.swing.JCheckBox InputStatus;
    private javax.swing.JTextField InputTanggalLahir;
    private javax.swing.JLabel LabelAlamat;
    private javax.swing.JLabel LabelDataMember;
    private javax.swing.JLabel LabelIDMember;
    private javax.swing.JLabel LabelKelolaMember;
    private javax.swing.JLabel LabelKontak;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JLabel LabelStatus;
    private javax.swing.JLabel LabelTanggalLahir;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelMember;
    // End of variables declaration//GEN-END:variables

    @Override
    public void valueChanged(ListSelectionEvent e) {
        if (e.getSource() == tabelMember.getSelectionModel()) {
            oldmember = daomember.getData(tabelMember.getSelectedRow());
            InputIDMember.setText(oldmember.getId());
            InputNama.setText(oldmember.getNama());
            InputAlamat.setText(oldmember.getAlamat());
            InputKontak.setText(oldmember.getKontak());
            InputTanggalLahir.setText(oldmember.getTanggallahir());
            InputStatus.setSelected(oldmember.isStatus());
        }
    }
}
