/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.DAOPinjaman;
import java.util.List;
import javax.swing.JOptionPane;
import model.Pinjaman;


public class PanelDetailPinjaman extends javax.swing.JPanel {

    /**
     * Creates new form PanelDetailPinjaman
     */
    DAOPinjaman daopinjam;
    public PanelDetailPinjaman() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelDetailPinjaman = new javax.swing.JLabel();
        LabelIDPinjam = new javax.swing.JLabel();
        InputIDPinjam = new javax.swing.JTextField();
        buttLihatDetailPinjaman = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputDetailPinjaman = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        LabelDetailPinjaman.setText("Detail Pinjaman");

        LabelIDPinjam.setText("ID Pinjam ");

        buttLihatDetailPinjaman.setText("Lihat Detail Pinjam");
        buttLihatDetailPinjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttLihatDetailPinjamanActionPerformed(evt);
            }
        });

        outputDetailPinjaman.setColumns(20);
        outputDetailPinjaman.setRows(5);
        jScrollPane1.setViewportView(outputDetailPinjaman);

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelDetailPinjaman)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelIDPinjam)
                            .addComponent(jButton1))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InputIDPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttLihatDetailPinjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelDetailPinjaman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelIDPinjam)
                    .addComponent(InputIDPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttLihatDetailPinjaman)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttLihatDetailPinjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttLihatDetailPinjamanActionPerformed
        search(daopinjam.getAllData(),InputIDPinjam.getText());
    }//GEN-LAST:event_buttLihatDetailPinjamanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void reset(){
        InputIDPinjam.setText("");
        outputDetailPinjaman.setText("");
    }
    public void setDAOPinjam(DAOPinjaman daopinjam){
        this.daopinjam = daopinjam;
    }
    public void search(List<Pinjaman> datapinjam, String x) {
        for (Pinjaman pinjaman : datapinjam) {
            if(pinjaman.getIDPinjam().equalsIgnoreCase(x)){
                outputDetailPinjaman.append(pinjaman.toString());
            }else{
                JOptionPane.showMessageDialog(this,"Data Kosong ","Confirmation Message", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputIDPinjam;
    private javax.swing.JLabel LabelDetailPinjaman;
    private javax.swing.JLabel LabelIDPinjam;
    private javax.swing.JButton buttLihatDetailPinjaman;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea outputDetailPinjaman;
    // End of variables declaration//GEN-END:variables
}
